# -*- coding: utf-8 -*-
"""CovidAjustado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xL_aQMRIICoQMJNAgWuOwaxFB8YWOh6u
"""

import pandas as pd

dados = pd.read_csv("https://raw.githubusercontent.com/lpgarcia18/covid_florianopolis/master/dados/covid_ajustado.csv")
dados.head()

dados.groupby('Resultado').size().plot(kind='bar')

dados.query('Resultado == "confirmado"').groupby('Bairro').size()