# -*- coding: utf-8 -*-
"""CovidAnonimizado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CE5wGf7XNRVEPST8-uSLpxh2CKuL3Snu
"""

import pandas as pd
import time
from sklearn import preprocessing
from sklearn.feature_extraction import FeatureHasher

#Faz a leitura do arquivo
dados = pd.read_csv('Dados/covid_ajustado.csv')
dados.shape

#Seleciona as colunas que contém informações
print(dados.isnull().sum().where(lambda x: x < len(dados)).dropna().index)

#Altera o NaN para missing
meusDados = dados.fillna('missing')
meusDados.head()

#Totaliza os dados da coluna Resultado
meusDados.groupby('RESULTADO').size()

#Conta qtos Município a base possui
meusDados['MUNICIPIO'].value_counts()
len(meusDados['MUNICIPIO'].value_counts())

#Conta qtos Territorios a base possui
meusDados['TERRITORIO'].value_counts()
len(meusDados.groupby('TERRITORIO').size())

#Conta qtos Subterritorios a base possui
meusDados['SUBTERRITORIO'].value_counts()
len(meusDados['SUBTERRITORIO'].value_counts())

#Faz um sumário dos dados de todas colunas
for coluna in meusDados.columns:
  print('Coluna: ', coluna)
  print(meusDados[coluna].value_counts())
  print('')

#Totaliza os dados da coluna Resultado por Território
meusDados.query('RESULTADO == "confirmado"')['TERRITORIO'].value_counts()

#Mostra uma breve descrição dos dados do Bairro
meusDados['TERRITORIO'].describe()

#Transforma str para date
meusDados['INICIO_SINTOMAS'] = pd.to_datetime(meusDados['INICIO_SINTOMAS'], errors='coerce')

#Exclui casos que não conseguiu converter a data
meusDados = meusDados.dropna(subset=['INICIO_SINTOMAS'])
meusDados.shape

###Faz a totalização dos casos confirmados por Território ###
confirmadosPorTerritorio = meusDados[['TERRITORIO', 'INICIO_SINTOMAS', 'RESULTADO']].query('RESULTADO == "confirmado"')
confirmadosPorTerritorio = pd.merge(meusDados, confirmadosPorTerritorio, how='left', on=['TERRITORIO', 'TERRITORIO'], suffixes=('_t1', '_t2'))

print(confirmadosPorTerritorio.shape)
confirmadosPorTerritorio.head()

confirmadosPorTerritorio['Diferenca_dias_sintomas'] = (confirmadosPorTerritorio['INICIO_SINTOMAS_t1'] - confirmadosPorTerritorio['INICIO_SINTOMAS_t2']).dt.days
confirmadosPorTerritorio = confirmadosPorTerritorio[(confirmadosPorTerritorio.Diferenca_dias_sintomas >= 0) & (confirmadosPorTerritorio.Diferenca_dias_sintomas <= 13)]

confirmadosPorTerritorio.head()

confirmados14Dias = confirmadosPorTerritorio.groupby(['ID']).size()
confirmados14Dias

###Faz a totalização dos casos descartados por Bairro ###
descartadosPorTerritorio = meusDados[['TERRITORIO', 'INICIO_SINTOMAS', 'RESULTADO']].query('RESULTADO == "descartado"')
descartadosPorTerritorio = pd.merge(meusDados, descartadosPorTerritorio, how='left', on=['TERRITORIO', 'TERRITORIO'], suffixes=('_t1', '_t2'))

print(descartadosPorTerritorio.shape)
descartadosPorTerritorio.head()

descartadosPorTerritorio['Diferenca_dias_sintomas'] = (descartadosPorTerritorio['INICIO_SINTOMAS_t1'] - descartadosPorTerritorio['INICIO_SINTOMAS_t2']).dt.days
descartadosPorTerritorio = descartadosPorTerritorio[(descartadosPorTerritorio.Diferenca_dias_sintomas >= 0)]

descartadosPorTerritorio.head()

descartados14Dias = descartadosPorTerritorio.groupby(['ID']).size()
descartados14Dias

###Faz a totalização dos casos removidos por Bairro ###
removidosPorTerritorio = meusDados[['TERRITORIO', 'INICIO_SINTOMAS', 'RESULTADO']].query('RESULTADO == "confirmado"')
removidosPorTerritorio = pd.merge(meusDados, removidosPorTerritorio, how='left', on=['TERRITORIO', 'TERRITORIO'], suffixes=('_t1', '_t2'))

print(removidosPorTerritorio.shape)
removidosPorTerritorio.head()

removidosPorTerritorio['Diferenca_dias_sintomas'] = (removidosPorTerritorio['INICIO_SINTOMAS_t1'] - removidosPorTerritorio['INICIO_SINTOMAS_t2']).dt.days
removidosPorTerritorio = removidosPorTerritorio[(removidosPorTerritorio.Diferenca_dias_sintomas >= 14)]

removidosPorTerritorio.head()

removidos = removidosPorTerritorio.groupby(['ID']).size()
removidos

###Junta os dados na tabela original ###
df = pd.merge(meusDados, pd.DataFrame(confirmados14Dias, columns=['Confirmados_territorio_14dias']), 
              how='left', on=['ID', 'ID'])
df = pd.merge(df, pd.DataFrame(descartados14Dias, columns=['Descartados_territorio_14dias']), 
              how='left', on=['ID', 'ID'])
df = pd.merge(df, pd.DataFrame(removidos, columns=['Removidos_territorio']), how='left', 
              on=['ID', 'ID'])
df.head()
df.columns

df.query('TERRITORIO == "cs_centro"').sort_values(by=['INICIO_SINTOMAS']).head(5)
    
#Define pra zero os registros com valor nulo
df.loc[df[df.Confirmados_territorio_14dias.isnull()].index, ['Confirmados_territorio_14dias']] = 0
df.loc[df[df.Descartados_territorio_14dias.isnull()].index, ['Descartados_territorio_14dias']] = 0
df.loc[df[df.Removidos_territorio.isnull()].index, ['Removidos_territorio']] = 0

df['Tx_Confirmados_territorio_14dias'] = df['Confirmados_territorio_14dias'] / df['populacao']
df['Tx_Removidos_territorio'] = df['Removidos_territorio'] / df['populacao']

#Deixa na base apenas os registros com Resultado igual a 'confirmado' ou 'descartado'
df = df.drop(df.query('RESULTADO != "confirmado" and RESULTADO != "descartado"').index)

#Transforma Resultado em código
df['RESULTADO'] = df['RESULTADO'].apply(lambda x: '0' if (x == 'descartado') else '1')

#Reset no índice para dar append nas colunas
df = df.reset_index()

#Transforma 'Data dos sintomas' em timestamp
df['INICIO_SINTOMAS'].isnull().sum()
df['INICIO_SINTOMAS'] = df['INICIO_SINTOMAS'].apply(lambda x: int(time.mktime(x.timetuple())))

# Formata a Idade com duas casas decimais
df['IDADE'] = df['IDADE'].map('{:,.2f}'.format)

#Exclui registros com Sexo 'missing'
df = df.drop(df[df.SEXO == 'missing'].index)

#Transforma Sexo em código
df['SEXO'] = df['SEXO'].apply(lambda x: '0' if (x == 'f') else '1')

#Transforma Territorio em hash
len(df.groupby('TERRITORIO').size())
fh = FeatureHasher(n_features=10, input_type='string')
hashTerritorio = fh.fit_transform(df['TERRITORIO'])
dfTerritorio = pd.DataFrame(fh.fit_transform(df['TERRITORIO']).toarray(), columns=['hf0', 'hf1', 
                            'hf2', 'hf3', 'hf4', 'hf5', 'hf6', 'hf7', 'hf8', 'hf9'])
df[dfTerritorio.columns] = dfTerritorio

#Transforma Raça em código
len(df.groupby('RACA_COR').size())
df['RACA_COR'].value_counts()
enc = preprocessing.OneHotEncoder()
dfRacaCor = pd.DataFrame(preprocessing.OneHotEncoder().fit_transform(df['RACA_COR'].to_frame()).
                         toarray(), columns=['rc0', 'rc1', 'rc2', 'rc3', 'rc4'])
df[dfRacaCor.columns] = dfRacaCor

#Transforma Triagem em código
len(df.groupby('TRIAGEM').size())
df.groupby('TRIAGEM').size()
dfTriagem = pd.DataFrame(preprocessing.OneHotEncoder().fit_transform(df['TRIAGEM'].to_frame()).
                         toarray(), columns=['tr0', 'tr1', 'tr2'])
df[dfTriagem.columns] = dfTriagem

#Retira algumas colunas
df = df.drop(columns=['index', 'ID', 'MUNICIPIO', 'TERRITORIO', 'SUBTERRITORIO', 'TRIAGEM', 
                      'FAIXA_ETARIA', 'RACA_COR'])
df.to_csv('Dados/novo_covid_ajustado.csv', index=False, header=True)